### ISSUE TITLE
How to get SAML assertion in step 2?

### ISSUE THREAD

**Issue by TechSkieur** [venkyvb/OAuthSAMLClient#1]
Hi venkyvb,

Very nice sample code, very helpful for us. Thank you a lot.

I have a question related to how to get SAML assertion in step 2? In our scenario, our app on YaaS platform wants to access a restful service API deployed on Sap Cloud Platform. This API can be accessed by oauth2 token. 

Our app is enabled with SSO, so we are thinking about using SAML assertion to call service's oauth2 service/endpoint to obtain token, but we are not clear how to get a bearer assertion...Call IDP to get it? And if we can get it, does it mean oauth2 also needs to have the functionality to receive SAML bearer assertion?

Thanks for your reply:)

**Comment by venkyvb** [comment]
Just to make sure that I understood your scenario: From a YaaS app you want to make a REST call to a service running on SAP Cloud Platform. Is this correct ?

For this I would not use OAuth SAML bearer flow, the easier approach would be to use OAuth client credentials flow. You can refer to the SAP Cloud Platform documentation around how this can be enabled.
